nameOverride: demo-app
fullnameOverride: ""

replicaCount: 1

image:
  repository: ghcr.io/maxanderson95/k8s-autoscaling/demo-app
  tag: 0.0.0-dev
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: "1"
    memory: 512Mi

service:
  port: 80
  targetPort: 8080

otel:
  endpoint: ""
  protocol: grpc
  headers: {}

serviceMonitor:
  enabled: true
  interval: 15s

maxMemoryMB: 1024